//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interfaces.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeriesUser", Namespace="http://schemas.datacontract.org/2004/07/servicio")]
    [System.SerializableAttribute()]
    public partial class SeriesUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NonmbreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TenerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VistaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nonmbre {
            get {
                return this.NonmbreField;
            }
            set {
                if ((object.ReferenceEquals(this.NonmbreField, value) != true)) {
                    this.NonmbreField = value;
                    this.RaisePropertyChanged("Nonmbre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Tener {
            get {
                return this.TenerField;
            }
            set {
                if ((this.TenerField.Equals(value) != true)) {
                    this.TenerField = value;
                    this.RaisePropertyChanged("Tener");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Vista {
            get {
                return this.VistaField;
            }
            set {
                if ((this.VistaField.Equals(value) != true)) {
                    this.VistaField = value;
                    this.RaisePropertyChanged("Vista");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnnimeNews", Namespace="http://schemas.datacontract.org/2004/07/servicio")]
    [System.SerializableAttribute()]
    public partial class AnnimeNews : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PubDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidField, value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PubDate {
            get {
                return this.PubDateField;
            }
            set {
                if ((this.PubDateField.Equals(value) != true)) {
                    this.PubDateField = value;
                    this.RaisePropertyChanged("PubDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        bool login(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        System.IAsyncResult Beginlogin(string user, string password, System.AsyncCallback callback, object asyncState);
        
        bool Endlogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaSeries", ReplyAction="http://tempuri.org/IService1/ListaSeriesResponse")]
        Interfaces.ServiceReference1.SeriesUser[] ListaSeries(string user);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ListaSeries", ReplyAction="http://tempuri.org/IService1/ListaSeriesResponse")]
        System.IAsyncResult BeginListaSeries(string user, System.AsyncCallback callback, object asyncState);
        
        Interfaces.ServiceReference1.SeriesUser[] EndListaSeries(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_vista_anime", ReplyAction="http://tempuri.org/IService1/update_vista_animeResponse")]
        void update_vista_anime(string user, bool tu, string anime);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/update_vista_anime", ReplyAction="http://tempuri.org/IService1/update_vista_animeResponse")]
        System.IAsyncResult Beginupdate_vista_anime(string user, bool tu, string anime, System.AsyncCallback callback, object asyncState);
        
        void Endupdate_vista_anime(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Get_listaquenotengo", ReplyAction="http://tempuri.org/IService1/Get_listaquenotengoResponse")]
        Interfaces.ServiceReference1.SeriesUser[] Get_listaquenotengo(string user);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Get_listaquenotengo", ReplyAction="http://tempuri.org/IService1/Get_listaquenotengoResponse")]
        System.IAsyncResult BeginGet_listaquenotengo(string user, System.AsyncCallback callback, object asyncState);
        
        Interfaces.ServiceReference1.SeriesUser[] EndGet_listaquenotengo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Añade_alista", ReplyAction="http://tempuri.org/IService1/Añade_alistaResponse")]
        void Añade_alista(string user, string Nombre, bool tu);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Añade_alista", ReplyAction="http://tempuri.org/IService1/Añade_alistaResponse")]
        System.IAsyncResult BeginAñade_alista(string user, string Nombre, bool tu, System.AsyncCallback callback, object asyncState);
        
        void EndAñade_alista(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNews", ReplyAction="http://tempuri.org/IService1/GetNewsResponse")]
        Interfaces.ServiceReference1.AnnimeNews[] GetNews();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetNews", ReplyAction="http://tempuri.org/IService1/GetNewsResponse")]
        System.IAsyncResult BeginGetNews(System.AsyncCallback callback, object asyncState);
        
        Interfaces.ServiceReference1.AnnimeNews[] EndGetNews(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Interfaces.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListaSeriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListaSeriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Interfaces.ServiceReference1.SeriesUser[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Interfaces.ServiceReference1.SeriesUser[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Get_listaquenotengoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Get_listaquenotengoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Interfaces.ServiceReference1.SeriesUser[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Interfaces.ServiceReference1.SeriesUser[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Interfaces.ServiceReference1.AnnimeNews[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Interfaces.ServiceReference1.AnnimeNews[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Interfaces.ServiceReference1.IService1>, Interfaces.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginloginDelegate;
        
        private EndOperationDelegate onEndloginDelegate;
        
        private System.Threading.SendOrPostCallback onloginCompletedDelegate;
        
        private BeginOperationDelegate onBeginListaSeriesDelegate;
        
        private EndOperationDelegate onEndListaSeriesDelegate;
        
        private System.Threading.SendOrPostCallback onListaSeriesCompletedDelegate;
        
        private BeginOperationDelegate onBeginupdate_vista_animeDelegate;
        
        private EndOperationDelegate onEndupdate_vista_animeDelegate;
        
        private System.Threading.SendOrPostCallback onupdate_vista_animeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGet_listaquenotengoDelegate;
        
        private EndOperationDelegate onEndGet_listaquenotengoDelegate;
        
        private System.Threading.SendOrPostCallback onGet_listaquenotengoCompletedDelegate;
        
        private BeginOperationDelegate onBeginAñade_alistaDelegate;
        
        private EndOperationDelegate onEndAñade_alistaDelegate;
        
        private System.Threading.SendOrPostCallback onAñade_alistaCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNewsDelegate;
        
        private EndOperationDelegate onEndGetNewsDelegate;
        
        private System.Threading.SendOrPostCallback onGetNewsCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<loginCompletedEventArgs> loginCompleted;
        
        public event System.EventHandler<ListaSeriesCompletedEventArgs> ListaSeriesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> update_vista_animeCompleted;
        
        public event System.EventHandler<Get_listaquenotengoCompletedEventArgs> Get_listaquenotengoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> Añade_alistaCompleted;
        
        public event System.EventHandler<GetNewsCompletedEventArgs> GetNewsCompleted;
        
        public bool login(string user, string password) {
            return base.Channel.login(user, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginlogin(string user, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginlogin(user, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool Endlogin(System.IAsyncResult result) {
            return base.Channel.Endlogin(result);
        }
        
        private System.IAsyncResult OnBeginlogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string user = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.Beginlogin(user, password, callback, asyncState);
        }
        
        private object[] OnEndlogin(System.IAsyncResult result) {
            bool retVal = this.Endlogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnloginCompleted(object state) {
            if ((this.loginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.loginCompleted(this, new loginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void loginAsync(string user, string password) {
            this.loginAsync(user, password, null);
        }
        
        public void loginAsync(string user, string password, object userState) {
            if ((this.onBeginloginDelegate == null)) {
                this.onBeginloginDelegate = new BeginOperationDelegate(this.OnBeginlogin);
            }
            if ((this.onEndloginDelegate == null)) {
                this.onEndloginDelegate = new EndOperationDelegate(this.OnEndlogin);
            }
            if ((this.onloginCompletedDelegate == null)) {
                this.onloginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnloginCompleted);
            }
            base.InvokeAsync(this.onBeginloginDelegate, new object[] {
                        user,
                        password}, this.onEndloginDelegate, this.onloginCompletedDelegate, userState);
        }
        
        public Interfaces.ServiceReference1.SeriesUser[] ListaSeries(string user) {
            return base.Channel.ListaSeries(user);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginListaSeries(string user, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListaSeries(user, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Interfaces.ServiceReference1.SeriesUser[] EndListaSeries(System.IAsyncResult result) {
            return base.Channel.EndListaSeries(result);
        }
        
        private System.IAsyncResult OnBeginListaSeries(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string user = ((string)(inValues[0]));
            return this.BeginListaSeries(user, callback, asyncState);
        }
        
        private object[] OnEndListaSeries(System.IAsyncResult result) {
            Interfaces.ServiceReference1.SeriesUser[] retVal = this.EndListaSeries(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListaSeriesCompleted(object state) {
            if ((this.ListaSeriesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListaSeriesCompleted(this, new ListaSeriesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListaSeriesAsync(string user) {
            this.ListaSeriesAsync(user, null);
        }
        
        public void ListaSeriesAsync(string user, object userState) {
            if ((this.onBeginListaSeriesDelegate == null)) {
                this.onBeginListaSeriesDelegate = new BeginOperationDelegate(this.OnBeginListaSeries);
            }
            if ((this.onEndListaSeriesDelegate == null)) {
                this.onEndListaSeriesDelegate = new EndOperationDelegate(this.OnEndListaSeries);
            }
            if ((this.onListaSeriesCompletedDelegate == null)) {
                this.onListaSeriesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListaSeriesCompleted);
            }
            base.InvokeAsync(this.onBeginListaSeriesDelegate, new object[] {
                        user}, this.onEndListaSeriesDelegate, this.onListaSeriesCompletedDelegate, userState);
        }
        
        public void update_vista_anime(string user, bool tu, string anime) {
            base.Channel.update_vista_anime(user, tu, anime);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginupdate_vista_anime(string user, bool tu, string anime, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginupdate_vista_anime(user, tu, anime, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void Endupdate_vista_anime(System.IAsyncResult result) {
            base.Channel.Endupdate_vista_anime(result);
        }
        
        private System.IAsyncResult OnBeginupdate_vista_anime(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string user = ((string)(inValues[0]));
            bool tu = ((bool)(inValues[1]));
            string anime = ((string)(inValues[2]));
            return this.Beginupdate_vista_anime(user, tu, anime, callback, asyncState);
        }
        
        private object[] OnEndupdate_vista_anime(System.IAsyncResult result) {
            this.Endupdate_vista_anime(result);
            return null;
        }
        
        private void Onupdate_vista_animeCompleted(object state) {
            if ((this.update_vista_animeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.update_vista_animeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void update_vista_animeAsync(string user, bool tu, string anime) {
            this.update_vista_animeAsync(user, tu, anime, null);
        }
        
        public void update_vista_animeAsync(string user, bool tu, string anime, object userState) {
            if ((this.onBeginupdate_vista_animeDelegate == null)) {
                this.onBeginupdate_vista_animeDelegate = new BeginOperationDelegate(this.OnBeginupdate_vista_anime);
            }
            if ((this.onEndupdate_vista_animeDelegate == null)) {
                this.onEndupdate_vista_animeDelegate = new EndOperationDelegate(this.OnEndupdate_vista_anime);
            }
            if ((this.onupdate_vista_animeCompletedDelegate == null)) {
                this.onupdate_vista_animeCompletedDelegate = new System.Threading.SendOrPostCallback(this.Onupdate_vista_animeCompleted);
            }
            base.InvokeAsync(this.onBeginupdate_vista_animeDelegate, new object[] {
                        user,
                        tu,
                        anime}, this.onEndupdate_vista_animeDelegate, this.onupdate_vista_animeCompletedDelegate, userState);
        }
        
        public Interfaces.ServiceReference1.SeriesUser[] Get_listaquenotengo(string user) {
            return base.Channel.Get_listaquenotengo(user);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGet_listaquenotengo(string user, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGet_listaquenotengo(user, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Interfaces.ServiceReference1.SeriesUser[] EndGet_listaquenotengo(System.IAsyncResult result) {
            return base.Channel.EndGet_listaquenotengo(result);
        }
        
        private System.IAsyncResult OnBeginGet_listaquenotengo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string user = ((string)(inValues[0]));
            return this.BeginGet_listaquenotengo(user, callback, asyncState);
        }
        
        private object[] OnEndGet_listaquenotengo(System.IAsyncResult result) {
            Interfaces.ServiceReference1.SeriesUser[] retVal = this.EndGet_listaquenotengo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGet_listaquenotengoCompleted(object state) {
            if ((this.Get_listaquenotengoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Get_listaquenotengoCompleted(this, new Get_listaquenotengoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Get_listaquenotengoAsync(string user) {
            this.Get_listaquenotengoAsync(user, null);
        }
        
        public void Get_listaquenotengoAsync(string user, object userState) {
            if ((this.onBeginGet_listaquenotengoDelegate == null)) {
                this.onBeginGet_listaquenotengoDelegate = new BeginOperationDelegate(this.OnBeginGet_listaquenotengo);
            }
            if ((this.onEndGet_listaquenotengoDelegate == null)) {
                this.onEndGet_listaquenotengoDelegate = new EndOperationDelegate(this.OnEndGet_listaquenotengo);
            }
            if ((this.onGet_listaquenotengoCompletedDelegate == null)) {
                this.onGet_listaquenotengoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGet_listaquenotengoCompleted);
            }
            base.InvokeAsync(this.onBeginGet_listaquenotengoDelegate, new object[] {
                        user}, this.onEndGet_listaquenotengoDelegate, this.onGet_listaquenotengoCompletedDelegate, userState);
        }
        
        public void Añade_alista(string user, string Nombre, bool tu) {
            base.Channel.Añade_alista(user, Nombre, tu);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAñade_alista(string user, string Nombre, bool tu, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAñade_alista(user, Nombre, tu, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndAñade_alista(System.IAsyncResult result) {
            base.Channel.EndAñade_alista(result);
        }
        
        private System.IAsyncResult OnBeginAñade_alista(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string user = ((string)(inValues[0]));
            string Nombre = ((string)(inValues[1]));
            bool tu = ((bool)(inValues[2]));
            return this.BeginAñade_alista(user, Nombre, tu, callback, asyncState);
        }
        
        private object[] OnEndAñade_alista(System.IAsyncResult result) {
            this.EndAñade_alista(result);
            return null;
        }
        
        private void OnAñade_alistaCompleted(object state) {
            if ((this.Añade_alistaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Añade_alistaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Añade_alistaAsync(string user, string Nombre, bool tu) {
            this.Añade_alistaAsync(user, Nombre, tu, null);
        }
        
        public void Añade_alistaAsync(string user, string Nombre, bool tu, object userState) {
            if ((this.onBeginAñade_alistaDelegate == null)) {
                this.onBeginAñade_alistaDelegate = new BeginOperationDelegate(this.OnBeginAñade_alista);
            }
            if ((this.onEndAñade_alistaDelegate == null)) {
                this.onEndAñade_alistaDelegate = new EndOperationDelegate(this.OnEndAñade_alista);
            }
            if ((this.onAñade_alistaCompletedDelegate == null)) {
                this.onAñade_alistaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAñade_alistaCompleted);
            }
            base.InvokeAsync(this.onBeginAñade_alistaDelegate, new object[] {
                        user,
                        Nombre,
                        tu}, this.onEndAñade_alistaDelegate, this.onAñade_alistaCompletedDelegate, userState);
        }
        
        public Interfaces.ServiceReference1.AnnimeNews[] GetNews() {
            return base.Channel.GetNews();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetNews(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNews(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Interfaces.ServiceReference1.AnnimeNews[] EndGetNews(System.IAsyncResult result) {
            return base.Channel.EndGetNews(result);
        }
        
        private System.IAsyncResult OnBeginGetNews(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetNews(callback, asyncState);
        }
        
        private object[] OnEndGetNews(System.IAsyncResult result) {
            Interfaces.ServiceReference1.AnnimeNews[] retVal = this.EndGetNews(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNewsCompleted(object state) {
            if ((this.GetNewsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNewsCompleted(this, new GetNewsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNewsAsync() {
            this.GetNewsAsync(null);
        }
        
        public void GetNewsAsync(object userState) {
            if ((this.onBeginGetNewsDelegate == null)) {
                this.onBeginGetNewsDelegate = new BeginOperationDelegate(this.OnBeginGetNews);
            }
            if ((this.onEndGetNewsDelegate == null)) {
                this.onEndGetNewsDelegate = new EndOperationDelegate(this.OnEndGetNews);
            }
            if ((this.onGetNewsCompletedDelegate == null)) {
                this.onGetNewsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNewsCompleted);
            }
            base.InvokeAsync(this.onBeginGetNewsDelegate, null, this.onEndGetNewsDelegate, this.onGetNewsCompletedDelegate, userState);
        }
    }
}
